#!/usr/bin/env python
# coding: utf-8
# created by hevlhayt@foxmail.com
# Date: 13-8-10 
# Time: 下午9:41
# 
permDic = dict(ACCESS_CHECKIN_PROPERTIES=0,
               ACCESS_COARSE_LOCATION=1,
               ACCESS_FINE_LOCATION=2,
               ACCESS_LOCATION_EXTRA_COMMANDS=3,
               ACCESS_MOCK_LOCATION=4,
               ACCESS_NETWORK_STATE=5,
               ACCESS_SURFACE_FLINGER=6,
               ACCESS_WIFI_STATE=7,
               ACCOUNT_MANAGER=8,
               ADD_VOICEMAIL=9,
               AUTHENTICATE_ACCOUNTS=10,
               BATTERY_STATS=11,
               BIND_ACCESSIBILITY_SERVICE=12,
               BIND_APPWIDGET=13,
               BIND_DEVICE_ADMIN=14,
               BIND_INPUT_METHOD=15,
               BIND_REMOTEVIEWS=16,
               BIND_TEXT_SERVICE=17,
               BIND_VPN_SERVICE=18,
               BIND_WALLPAPER=19,
               BLUETOOTH=20,
               BLUETOOTH_ADMIN=21,
               BRICK=22,
               BROADCAST_PACKAGE_REMOVED=23,
               BROADCAST_SMS=24,
               BROADCAST_STICKY=25,
               BROADCAST_WAP_PUSH=26,
               CALL_PHONE=27,
               CALL_PRIVILEGED=28,
               CAMERA=29,
               CHANGE_COMPONENT_ENABLED_STATE=30,
               CHANGE_CONFIGURATION=31,
               CHANGE_NETWORK_STATE=32,
               CHANGE_WIFI_MULTICAST_STATE=33,
               CHANGE_WIFI_STATE=34,
               CLEAR_APP_CACHE=35,
               CLEAR_APP_USER_DATA=36,
               CONTROL_LOCATION_UPDATES=37,
               DELETE_CACHE_FILES=38,
               DELETE_PACKAGES=39,
               DEVICE_POWER=40,
               DIAGNOSTIC=41,
               DISABLE_KEYGUARD=42,
               DUMP=43,
               EXPAND_STATUS_BAR=44,
               FACTORY_TEST=45,
               FLASHLIGHT=46,
               FORCE_BACK=47,
               GET_ACCOUNTS=48,
               GET_PACKAGE_SIZE=49,
               GET_TASKS=50,
               GLOBAL_SEARCH=51,
               HARDWARE_TEST=52,
               INJECT_EVENTS=53,
               INSTALL_LOCATION_PROVIDER=54,
               INSTALL_PACKAGES=55,
               INTERNAL_SYSTEM_WINDOW=56,
               INTERNET=57,
               KILL_BACKGROUND_PROCESSES=58,
               MANAGE_ACCOUNTS=59,
               MANAGE_APP_TOKENS=60,
               MASTER_CLEAR=61,
               MODIFY_AUDIO_SETTINGS=62,
               MODIFY_PHONE_STATE=63,
               MOUNT_FORMAT_FILESYSTEMS=64,
               MOUNT_UNMOUNT_FILESYSTEMS=65,
               NFC=66,
               PERSISTENT_ACTIVITY=67,
               PROCESS_OUTGOING_CALLS=68,
               READ_CALENDAR=69,
               READ_CALL_LOG=70,
               READ_CONTACTS=71,
               READ_EXTERNAL_STORAGE=72,
               READ_FRAME_BUFFER=73,
               READ_HISTORY_BOOKMARKS=74,
               READ_INPUT_STATE=75,
               READ_LOGS=76,
               READ_PHONE_STATE=77,
               READ_PROFILE=78,
               READ_SMS=79,
               READ_SOCIAL_STREAM=80,
               READ_SYNC_SETTINGS=81,
               READ_SYNC_STATS=82,
               READ_USER_DICTIONARY=83,
               REBOOT=84,
               RECEIVE_BOOT_COMPLETED=85,
               RECEIVE_MMS=86,
               RECEIVE_SMS=87,
               RECEIVE_WAP_PUSH=88,
               RECORD_AUDIO=89,
               REORDER_TASKS=90,
               RESTART_PACKAGES=91,
               SEND_SMS=92,
               SET_ACTIVITY_WATCHER=93,
               SET_ALARM=94,
               SET_ALWAYS_FINISH=95,
               SET_ANIMATION_SCALE=96,
               SET_DEBUG_APP=97,
               SET_ORIENTATION=98,
               SET_POINTER_SPEED=99,
               SET_PREFERRED_APPLICATIONS=100,
               SET_PROCESS_LIMIT=101,
               SET_TIME=102,
               SET_TIME_ZONE=103,
               SET_WALLPAPER=104,
               SET_WALLPAPER_HINTS=105,
               SIGNAL_PERSISTENT_PROCESSES=106,
               STATUS_BAR=107,
               SUBSCRIBED_FEEDS_READ=108,
               SUBSCRIBED_FEEDS_WRITE=109,
               SYSTEM_ALERT_WINDOW=110,
               UPDATE_DEVICE_STATS=111,
               USE_CREDENTIALS=112,
               USE_SIP=113,
               VIBRATE=114,
               WAKE_LOCK=115,
               WRITE_APN_SETTINGS=116,
               WRITE_CALENDAR=117,
               WRITE_CALL_LOG=118,
               WRITE_CONTACTS=119,
               WRITE_EXTERNAL_STORAGE=120,
               WRITE_GSERVICES=121,
               WRITE_HISTORY_BOOKMARKS=122,
               WRITE_PROFILE=123,
               WRITE_SECURE_SETTINGS=124,
               WRITE_SETTINGS=125,
               WRITE_SMS=126,
               WRITE_SOCIAL_STREAM=127,
               WRITE_SYNC_SETTINGS=128,
               WRITE_USER_DICTIONARY=129,
               OTHERS=130)

redFlags = {"SEND_SMS": "MONEY, SMS",
            "READ_SMS": "SMS, PRIVACY",
            "WRITE_SMS": "MONEY, SMS",
            "RECEIVE_SMS": "SMS, PRIVACY",
            "RECEIVE_MMS": "SMS, PRIVACY",

            "PHONE_CALL": "MONEY, CALL",
            "PROCESS_OUTGOING_CALLS": "MONEY, CALL",
            "CALL_PRIVILEGED": "MONEY, CALL",

            "INTERNET": "INTERNET",

            "READ_PHONE_STATE": "PRIVACY",

            "READ_CONTACTS": "PRIVACY",
            "WRITE_CONTACTS": "PRIVACY",

            "READ_HISTORY_BOOKMARKS": "PRIVACY",
            "WRITE_HISTORY_BOOKMARKS": "PRIVACY",

            "READ_PROFILE": "PRIVACY",
            "WRITE_PROFILE": "PRIVACY",

            "READ_SOCIAL_STREAM": "PRIVACY",
            "WRITE_SOCIAL_STREAM": "PRIVACY",

            "READ_CALENDAR": "PRIVACY",
            "WRITE_CALENDAR": "PRIVACY",

            "READ_USER_DICTIONARY": "PRIVACY",
            "WRITE_USER_DICTIONARY": "PRIVACY",

            "SET_ALARM": "PRIVACY",

            "ADD_VOICEMAIL": "PRIVACY",

            "GET_ACCOUNTS": "PRIVACY",
            "MANAGE_ACCOUNTS": "PRIVACY",

            "RECORD_AUDIO": "PRIVACY",
            "CAMERA": "PRIVACY",


            "ACCESS_FINE_LOCATION": "PRIVACY, GPS",
            "ACCESS_COARSE_LOCATION": "PRIVACY, GPS",
            "ACCESS_LOCATION_EXTRA_COMMANDS": "GPS",
            "INSTALL_LOCATION_PROVIDER": "GPS"
            }